---
title: "1.2 Why DBMS?/1"
date: "2026-02-10"
---

# Why DBMS? 

- This Module's objective is to understand the need of DBMS from a historical perspective. We will look at as a society how we have evolved and how the technology has evolved over years.

- In the next video, we will learn why we need specific type of systems for solving data related problems, instead of simple computer programs.


## Evolution of Data Management

Let's see what were all the requirements needed in the society back then? 

1. **Storage and retrieval** : How do we store data and retrieve a particular information. The first thing is storage & retieval.
2. **Transaction** : Something is being exchanged or moved from one place to another, like a financial transaction.
3. **Audit** : Did things happen properly, all rules and regulations are properly followed. Ex : Like tax paid,

4. **Archival** : Keeping data for later, maybe using it later for some purpose.


- Whom we do it for ? 

1. Individuals
2. Small / Big Enterprise
3. Global organization

There are two major approaches in practice : 
<br>
1. Physical  <br>
2. Electronic


## Physical 

Physical Data Records or Records Management, known as "Book Keeping". <br>

- Writing down everything is laborious and error prone. So, Herman Hollerith brought punching cards that were used in the Jacquard Loom to do a very simple mechanical computation based on ledgers. 

This was folowed till the middle of the 20th century.

## Electronic 

This started when computers and programs started.

- IN 1950s computers programming started.
- In 1960s, data was stored in punch cards and then moved to magnetic tapes. This went on untill 10 - 15 years till 1970s, when certain significant improvements and developments happened . 

- In 1970s, COBOL was introduced 50 years ago and is still used till date. CODASYL approach was one approach for data management.
<br>
In 1979, Apple introduced VisiCalc marking the birth of spreasheet, which is the great grandfather of Excel, etc. Then later on Excel, Google Sheets came in. 
<br>
Magnetic tapes became widespread.

- In 1980s , Relational Database Management Systems changed the face of data management.
- IN 1990s, the Internet came which made the whole data and management records global. 
- In 2000s, the **E-commerce** boomed, all the E - commerce companies were started, which caused the requirement of storing **unstructured** data , i.e. data about images, video and audio and Natural Language text, when NoSQL was born. 
- In 2010s, the Data Science took over riding the wave.



### Electronic Data Parameters 

There are several parameters on which the data and records management system particullarly depends :

- **Durability** : The data must be available for ages, which was a basic drawback of the physical system. There were many reasons : like termite, acid in the paper would decay.

- **Scalability** : The system should be scalable for 100s, 1000s ,1M or billions of users.

- **Secured** : Based on the application the security will differ, like for a defense application, it needs highest security and compared to defense for a digital library system will be far less.

- **Retrieval** : How quickly we can retrieve the data? like within a day, hours or seconds.

- **Ease of Use** : It should be easy to use, otherwise it has not served the purpose.

- **Consistency** : The database must be in a consistent state, before and after the transaction.

- **Efficiency** : Efficiency must be high.


## Book - Keeping 

There are still grocery shop owners who maintain book registers for data management. Some might have a small PC , some might do on  mobile, but there are still many grocery and medical shops who maintain their stock required in notes.

<br>

Problems with book - keeping : 

**Durability**: Physical damage can happen due to rodents, wear and tear, moisture and humidity.

**Scalability** : Scalability  is very difficult to maintain on ledgers. We can maintain records of 100 to 200 customers in physical records, but is not possible to store millions of customers on paper.

**Security** :  We need lockers, and is susceptible to tamper by outsiders.

**Retrieval** : It is time - consuming to retrieve data from records.

**Consistency** : It is prone to errors, if transaction debited and credited are not written together.

## Spreadsheets 

Spreadheets came in about 40 years back. Applications like Excel and Google Sheets use the spreadsheet software.

- **Durability** : Spreadsheets are computer applications and we can Google Sheets in the cloud, which will be stored in the Google infrastructure.

- **Scalability** : It is easier to search, insert and modify records of large numbers.

- **Security** : It can be password - protected. Although this protection can be bypassed by other methods, it is better than book - keeping.

- **Ease of Use** : It is easy to use. It is easier to perform computational operations on the data.

- **Consistency** : It is not guaranteed in spreadsheets, we have to either write lots of formulas or make sure it is written in a right manner.

<br>
These are still used for single user or small enterprise applications.

## Why leave File Systems ? 

- With the increase in scale of data, the time to taken to perform operations on data increases.
- A spreadsheet has a limit on the number of rows.
- Consistency is a big issue challenge.
- Constraints : If we certain constraints in data. Excel allows us to put some constraints, but they are just data entry constraints, like we cannot enter a negative value in a cell.
But constraints related to transactions is very difficult to maintain in file-based systems, because we need to write separate code for each condition.
- Permission levels are limited, we can keep a password but we cannot give multiple users use the same file at various levels of authority.

### History of DBMS 

- In 1950s and 1960s magnetic tapes and punch cards were there for storage.
- Late 1960s and 1970s hard disks came in and allowed direct access to data.
- Ted Codd defines the relational model.
- 80s saw the parallelization and distribution of database systems.

Before that Database systems were centralized, which means we had one PC, server or machine we were using in.

- In 1980s, across the enterprise it was started using, across the local area network.
- In 1990s, as the Internet came in the distribution went across the web.
- In early 2000s, the need for structured and unstructured data management came in so we had XML and XQuery
- Later 2000s , giant data storage systems - Google BigTable , Yahoo, Amazon.

> Foundation of datascience is not database, it is the database system, which gives data warehousing , data mining , etc of which we are trying to gain expertise about.

This course will cover mainly on the Client Server RDBMS like Oracle , Sybase, Postgres, etc.